passthruUnmapped: false

media:
  image:
    library:
      - src: https://images.microcms-assets.io/assets/
        kind: imgix

flds:
  - srcName: title
    dstName: title
    fldType: string

  - srcName: content
    dstName: content
    fldType: html
    convert: markdown
    toMarkdownOpts:
      imageSalt:
        - command: embed
          baseURL: https://images.microcms-assets.io/assets/
          embed:
            embedTo: alt

  - srcName: description
    dstName: description
    fldType: string

  - srcName: category.label["ja" in lang].label
    dstName: category
    fldType: string

  - srcName: fullscreen
    dstName: fullscreen
    fldType: boolean

  - srcName: version
    dstName: version
    fldType: string

  - srcName: menuTitle
    dstName: menuTitle
    fldType: string

  - srcName: subtitle
    dstName: subtitle
    fldType: string

  - srcName: badge
    dstName: badge
    fldType: string

  - srcName: list
    dstName: list
    fldType: object

  - srcName: category.label["ja" in lang].label
    dstName: category
    fldType: string

  - srcName: '$count(list)>0 ? list{title:items[fieldId="item"].item} : {}'
    dstName: list
    fldType: object
