passthruUnmapped: false
selectFldsToFetch: true

media:
  image:
    library:
      - src: https://images.microcms-assets.io/assets/
        kind: imgix

flds:
  - fetchFld: title
    query: title
    dstName: title
    fldType: string

  - fetchFld: content
    query: content
    dstName: content
    fldType: html
    convert: markdown
    toMarkdownOpts:
      imageSalt:
        - command: embed
          baseURL: https://images.microcms-assets.io/assets/
          embed:
            embedTo: alt
      unusualSpaceChars: throw

  - fetchFld: description
    query: description
    dstName: description
    fldType: string

  - fetchFld: category.label
    query: category.label["en" in lang].label
    dstName: category
    fldType: string

  - fetchFld: fullscreen
    query: fullscreen
    dstName: fullscreen
    fldType: boolean

  - fetchFld: version
    query: version
    dstName: version
    fldType: string

  - fetchFld: menuTitle
    query: menuTitle
    dstName: menuTitle
    fldType: string

  - fetchFld: subtitle
    query: subtitle
    dstName: subtitle
    fldType: string

  - fetchFld: badge
    query: badge
    dstName: badge
    fldType: string

  - fetchFld: list
    query: '$count(list)>0 ? list{title:items[fieldId="item"].item} : {}'
    dstName: list
    fldType: object
