passthruUnmapped: true

media:
  image:
    library:
      - src: https://images.microcms-assets.io/assets/
        kind: imgix

flds:
  - query: title
    dstName: title
    fldType: string

  - query: content
    dstName: content
    fldType: html
    convert: markdown
    toMarkdownOpts:
      imageSalt:
        - command: embed
          baseURL: https://images.microcms-assets.io/assets/
          embed:
            embedTo: alt

  - query: description
    dstName: description
    fldType: string

  - query: '$count(list)>0 ? list{title:items[fieldId="item"].item} : {}'
    dstName: category
    fldType: string

  - query: fullscreen
    dstName: fullscreen
    fldType: boolean

  - query: version
    dstName: version
    fldType: string

  - query: menuTitle
    dstName: menuTitle
    fldType: string

  - query: subtitle
    dstName: subtitle
    fldType: string

  - query: badge
    dstName: badge
    fldType: string

  - query: list
    dstName: list
    fldType: object

  - query: category.label["ja" in lang].label
    dstName: category
    fldType: string

  - query: '$count(list)>0 ? list{title:items[fieldId="item"].item} : {}'
    dstName: list
    fldType: object
